version: '2'
jobs:
  build:
    working_directory: /go/src/github.com/qri-io/startf
    docker:
      - image: circleci/golang:1.11
        environment:
          GOLANG_ENV: test
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report golang.org/x/lint/golint
      - run:
          name: Install non-gx deps
          command: >
            go get -v -d -u
            github.com/jstemmer/go-junit-report 
            github.com/qri-io/cafs
            github.com/qri-io/dataset
            github.com/google/skylark
            github.com/google/skylark/repl
            github.com/google/skylark/resolve
            github.com/qri-io/dataset
            github.com/qri-io/dataset/dsio
            github.com/qri-io/ioes
            github.com/PuerkitoBio/goquery
            github.com/360EntSecGroup-Skylar/excelize
      - run: 
          name: Run Lint Tests
          command: golint -set_exit_status ./... 
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install gx
          command: >
            go get -v
            github.com/whyrusleeping/gx 
            github.com/whyrusleeping/gx-go
      - run:
          name: Install gx deps
          command: gx install
      - run:
          name: Install gx-dependant packages
          command: >
            go get -v -d
            github.com/qri-io/startf
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - /go/src/gx/
      - run:
          name: Run Tests
          command: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Publish coverage info to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
